// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcInheritedDHCPOption InheritedDHCPOption
//
// The inheritance configuration for a field of type of _OptionItem_.
//
// swagger:model ipamsvcInheritedDHCPOption
func dataSourceIpamsvcInheritedDHCPOption() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _block_: Don't use the inherited value.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _block_: Don't use the inherited value.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The inherited value for the DHCP option.
			// Read Only: true
			"value": {
				Type:        schema.TypeList,
				Elem:        dataSourceIpamsvcOptionItem(),
				Computed:    true,
				Description: "The inherited value for the DHCP option.",
			},
		},
	}
}
