// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcAsmGrowthBlock AsmGrowthBlock
//
// ASM growth group of fields.
//
// swagger:model ipamsvcAsmGrowthBlock
func dataSourceIpamsvcAsmGrowthBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// Either the number or percentage of addresses to grow by.
			"growth_factor": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Either the number or percentage of addresses to grow by.",
			},

			// The type of factor to use: _percent_ or _count_.
			"growth_type": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The type of factor to use: _percent_ or _count_.",
			},
		},
	}
}
