// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcDDNSHostnameBlock DDNSHostnameBlock
//
// The dynamic DNS Hostname configuration.
//
// swagger:model ipamsvcDDNSHostnameBlock
func resourceIpamsvcDDNSHostnameBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// Indicates if DDNS should generate a hostname when not supplied by the client.
			"ddns_generate_name": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Indicates if DDNS should generate a hostname when not supplied by the client.",
			},

			// The prefix used in the generation of an FQDN.
			"ddns_generated_prefix": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The prefix used in the generation of an FQDN.",
			},
		},
	}
}
