// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcDDNSUpdateBlock DDNSBlock
//
// The dynamic DNS configurations, ddns_domain and ddns_send_updates.
//
// swagger:model ipamsvcDDNSUpdateBlock
func dataSourceIpamsvcDDNSUpdateBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The domain name for DDNS.
			"ddns_domain": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The domain name for DDNS.",
			},

			// Determines if DDNS updates are enabled at this level.
			"ddns_send_updates": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Determines if DDNS updates are enabled at this level.",
			},
		},
	}
}
