// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcInheritedDHCPConfig InheritedDHCPConfig
//
// The inheritance configuration for a field of type _DHCPConfig_.
//
// swagger:model ipamsvcInheritedDHCPConfig
func dataSourceIpamsvcInheritedDHCPConfig() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance configuration for _allow_unknown_ field from _DHCPConfig_ object.
			"allow_unknown": {
				Type:        schema.TypeList,
				Elem:        dataSourceInheritanceInheritedBool(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _allow_unknown_ field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for filters field from _DHCPConfig_ object.
			"filters": {
				Type:        schema.TypeList,
				Elem:        dataSourceInheritedDHCPConfigFilterList(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for filters field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for _ignore_list_ field from _DHCPConfig_ object.
			"ignore_list": {
				Type:        schema.TypeList,
				Elem:        dataSourceInheritedDHCPConfigIgnoreItemList(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _ignore_list_ field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for _lease_time_ field from _DHCPConfig_ object.
			"lease_time": {
				Type:        schema.TypeList,
				Elem:        dataSourceInheritanceInheritedUInt32(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _lease_time_ field from _DHCPConfig_ object.",
			},
		},
	}
}
