// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

// IpamsvcAsmEnableBlock AsmEnableBlock
//
// ASM enable group of fields.
//
// swagger:model ipamsvcAsmEnableBlock
func dataSourceIpamsvcAsmEnableBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// Indicates whether Automated Scope Management is enabled or not.
			"enable": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Indicates whether Automated Scope Management is enabled or not.",
			},

			// Indicates whether sending notifications to the users is enabled or not.
			"enable_notification": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Indicates whether sending notifications to the users is enabled or not.",
			},

			// The date at which notifications will be re-enabled automatically.
			// Format: date-time
			"reenable_date": {
				Type:         schema.TypeString,
				Optional:     true,
				Description:  "The date at which notifications will be re-enabled automatically.",
				ValidateFunc: validation.IsRFC3339Time,
			},
		},
	}
}
