// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcIgnoreItem IgnoreItem
//
// An Ignore Item object (_dhcp/ignore_item_) represents an item in a DHCP ignore list.
//
// swagger:model ipamsvcIgnoreItem
func dataSourceIpamsvcIgnoreItem() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// Type of ignore matching: client to ignore by client identifier (client hex or client text) or hardware to ignore by hardware identifier (MAC address). It can have one of the following values:
			//  * _client_hex_,
			//  * _client_text_,
			//  * _hardware_.
			// Required: true
			"type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Type of ignore matching: client to ignore by client identifier (client hex or client text) or hardware to ignore by hardware identifier (MAC address). It can have one of the following values:\n * _client_hex_,\n * _client_text_,\n * _hardware_.",
			},

			// Value to match.
			// Required: true
			"value": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Value to match.",
			},
		},
	}
}
