// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcInheritedDHCPOptionList InheritedDHCPOptionList
//
// The inheritance configuration for a field that contains list of _OptionItem_.
//
// swagger:model ipamsvcInheritedDHCPOptionList
func dataSourceIpamsvcInheritedDHCPOptionList() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _block_: Don't use the inherited value.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _block_: Don't use the inherited value.\n\nDefaults to _inherit_.",
			},

			// The inherited DHCP option values.
			"value": {
				Type:        schema.TypeList,
				Elem:        dataSourceIpamsvcInheritedDHCPOption(),
				Optional:    true,
				Description: "The inherited DHCP option values.",
			},
		},
	}
}
