// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// IpamsvcDHCPOptionsInheritance DHCPOptionsInheritance
//
// The inheritance configuration that specifies how the _dhcp_options_ field is inherited from the parent object.
//
// swagger:model ipamsvcDHCPOptionsInheritance
func schemaIpamsvcDHCPOptionsInheritance() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			// The inheritance configuration for the _dhcp_options_ field.
			"dhcp_options": {
				Type:        schema.TypeList,
				Elem:        schemaIpamsvcInheritedDHCPOptionList(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for the _dhcp_options_ field.",
			},
		},
	}
}
