// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcHostnameRewriteBlock HostnameRewriteBlock
//
// Hostname Rewrite grouping fields.
//
// swagger:model ipamsvcHostnameRewriteBlock
func schemaIpamsvcHostnameRewriteBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance configuration for _hostname_rewrite_char_ field.
			"hostname_rewrite_char": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance configuration for _hostname_rewrite_char_ field.",
			},

			// The inheritance configuration for _hostname_rewrite_enabled_ field.
			"hostname_rewrite_enabled": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "The inheritance configuration for _hostname_rewrite_enabled_ field.",
			},

			// The inheritance configuration for _hostname_rewrite_regex_ field.
			"hostname_rewrite_regex": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance configuration for _hostname_rewrite_regex_ field.",
			},
		},
	}
}

func flattenIpamsvcHostnameRewriteBlock(r *models.IpamsvcHostnameRewriteBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	res := make(map[string]interface{})

	res["hostname_rewrite_char"] = r.HostnameRewriteChar
	res["hostname_rewrite_enabled"] = r.HostnameRewriteEnabled
	res["hostname_rewrite_regex"] = r.HostnameRewriteRegex

	return []interface{}{res}
}
