// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcDDNSUpdateBlock DDNSBlock
//
// The dynamic DNS configurations, ddns_domain and ddns_send_updates.
//
// swagger:model ipamsvcDDNSUpdateBlock
func schemaIpamsvcDDNSUpdateBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The domain name for DDNS.
			"ddns_domain": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The domain name for DDNS.",
			},

			// Determines if DDNS updates are enabled at this level.
			"ddns_send_updates": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Determines if DDNS updates are enabled at this level.",
			},
		},
	}
}

func flattenIpamsvcDDNSUpdateBlock(r *models.IpamsvcDDNSUpdateBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	res := make(map[string]interface{})

	res["ddns_domain"] = r.DdnsDomain
	res["ddns_send_updates"] = r.DdnsSendUpdates

	return []interface{}{res}

}
